### PR TITLE
Add ci.yml

### PR DESCRIPTION
**Pull request by ortoLover**
Implementation of CI and SonarCloud

### CODE REVIEW

**Comment by SidonieBouthors** [comment]
Closes #5

**Comment by SidonieBouthors** [comment]
We're good for the google-services.json for Firebase tests :) Just need to upload CI reports to SonarCloud and this should be good to go

**Review by SidonieBouthors — APPROVED** [review]
LGTM :) We might need to look into the SonarCloud settings more on their website but I think this is good to merge

**Comment by Polymeth** [comment]
LGTM with the config file now! In the future, still need to config precisely Sonarcloud on the admin panel however.

**Pull request merged**
