### PR TITLE
Viewmodel : members management

### LINKED ISSUE #378: VM members management
Viewmodel for the members management in the association settings.

- [ ] Remove the invitation (applicants)
- [ ] Edit someone's role
- [ ] Remove someone (+ with confirmation)

### PR DESCRIPTION
**Pull request by Mai-LinhC**
closes #378 

- [x]  Remove the invitation (applicants) since it won't be done in V1
- [x] Dialog to edit member('s role)
- [x]  Edit someone's role
- [x] Dialog to remove member from asso
- [x]  Remove someone after confirmation
- [x] Test for edit
- [x] Test for delete

### CODE REVIEW

**Comment by Mai-LinhC** [comment]
- Functionalities need some API functions that are not yet done
- The dialogs open only after touching the screen ? Need to figure out why
- The edit dialog looks wonky and the spacings look wrong, no idea why yet

**Comment by Mai-LinhC** [comment]
> * Functionalities need some API functions that are not yet done
> * The dialogs open only after touching the screen ? Need to figure out why
> * The edit dialog looks wonky and the spacings look wrong, no idea why yet

* waiting for API
* the bug with the dialog is just on the emulator, works perfectly well on device
* dialog looks fine on device, it's just list items

**Review by sarahbadr17 — COMMENTED** [review]
I found a bug. I don't know if it's normal or not
photo_2024-06-02_23-32-40
When Selecting Associfiy as a member I couldn't change its role

**Review by sarahbadr17 — APPROVED** [review]
Seems to be normal after second thought

**Comment by Mai-LinhC** [comment]
> Seems to be normal after second thought

I can't reproduce the bug at all, but seeing the snackbar it's an API fail, so it should be fine

**Pull request merged**
